/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/leagues": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Leagues */
        get: operations["list_leagues_api_leagues_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/leagues/{league}/ratings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Ratings */
        get: operations["get_ratings_api_leagues__league__ratings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LeagueSummary */
        LeagueSummary: {
            /** League */
            league: string;
            /** Models */
            models: components["schemas"]["ModelSummary"][];
        };
        /**
         * Metrics
         * @description Evaluation metrics for a release.
         *
         *     `brier_score` is an error measure, so lower is better -- see
         *     `pick_default` in releases.py, which is the one place that matters.
         */
        Metrics: {
            /** Against Spread Accuracy */
            against_spread_accuracy?: number | null;
            /** Brier Score */
            brier_score: number;
            /** N Games */
            n_games: number;
            /**
             * N Spread Games
             * @default 0
             */
            n_spread_games: number;
        };
        /** ModelSummary */
        ModelSummary: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Is Default */
            is_default: boolean;
            metrics: components["schemas"]["Metrics"];
            /** Name */
            name: string;
            /** Run Id */
            run_id: string;
        };
        /** RatingsResponse */
        RatingsResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** League */
            league: string;
            metrics: components["schemas"]["Metrics"];
            /** Model */
            model: string;
            /** Ratings */
            ratings: components["schemas"]["TeamRow"][];
            /** Run Id */
            run_id: string;
            trained_through: components["schemas"]["TrainedThrough"];
        };
        /** TeamRow */
        TeamRow: {
            /** Losses */
            losses: number;
            /** Rank */
            rank: number;
            /** Rating */
            rating: number;
            /** Rd */
            rd: number | null;
            /** Team */
            team: string;
            /** Wins */
            wins: number;
        };
        /**
         * TrainedThrough
         * @description Watermark for the incremental refresh job.
         *
         *     `processed_game_ids` is a set of ids rather than a timestamp because games
         *     get re-fetched and scores corrected; ids are what make the refresh
         *     idempotent. Current season only -- it's a resume marker, not an audit log.
         */
        TrainedThrough: {
            /** Last Game Date */
            last_game_date?: string | null;
            /** Processed Game Ids */
            processed_game_ids?: string[];
            /** Season Year */
            season_year: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_leagues_api_leagues_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeagueSummary"][];
                };
            };
        };
    };
    get_ratings_api_leagues__league__ratings_get: {
        parameters: {
            query?: {
                /** @description Defaults to the league's lowest-Brier model. */
                model?: string | null;
            };
            header?: never;
            path: {
                league: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RatingsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
