/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Jobs */
        get: operations["get_jobs_api_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/volume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Volume */
        get: operations["get_volume_api_jobs_volume_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/leagues": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Leagues */
        get: operations["list_leagues_api_leagues_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/leagues/{league}/ratings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Ratings */
        get: operations["get_ratings_api_leagues__league__ratings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/predict": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Predict */
        get: operations["predict_api_predict_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * JobHealth
         * @description One job definition's runs over the window, rolled up.
         */
        JobHealth: {
            /** Failed */
            failed: number;
            /** Kind */
            kind: string;
            last_run: components["schemas"]["JobRun"] | null;
            /** Last Success At */
            last_success_at: string | null;
            /** League */
            league: string | null;
            /** Name */
            name: string;
            /** Recent */
            recent: components["schemas"]["JobRun"][];
            /** Running */
            running: number;
            /** Runs */
            runs: number;
            /** Succeeded */
            succeeded: number;
            /** Success Rate */
            success_rate: number | null;
        };
        /**
         * JobRun
         * @description One Batch job run.
         */
        JobRun: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Definition */
            definition: string;
            /**
             * Duration Seconds
             * @description Wall time in the container, not counting time spent RUNNABLE.
             *
             *     Queue wait is a property of the queue rather than of the job, and
             *     folding it in would make every job look slow whenever something big is
             *     ahead of it.
             */
            readonly duration_seconds: number | null;
            /** Exit Code */
            exit_code?: number | null;
            /** Job Id */
            job_id: string;
            /** Name */
            name: string;
            /** Started At */
            started_at?: string | null;
            /** Status */
            status: string;
            /** Status Reason */
            status_reason?: string | null;
            /** Stopped At */
            stopped_at?: string | null;
        };
        /** JobsResponse */
        JobsResponse: {
            /** Jobs */
            jobs: components["schemas"]["JobHealth"][];
            /**
             * Since
             * Format: date-time
             */
            since: string;
            /** Truncated */
            truncated: boolean;
            /** Window Days */
            window_days: number;
        };
        /** LeagueSummary */
        LeagueSummary: {
            /** League */
            league: string;
            /** Models */
            models: components["schemas"]["ModelSummary"][];
        };
        /**
         * Metrics
         * @description Evaluation metrics for a release.
         *
         *     `brier_score` and the MAEs are error measures, so lower is better -- a
         *     consumer picking a default model wants a min, not a max.
         *
         *     The optional fields are None for a league the odds database doesn't cover
         *     at all. They're None rather than nan on purpose: `score_predictions`
         *     returns nan there, and nan survives json.dumps as the literal `NaN`, which
         *     is not valid JSON and which browsers reject.
         */
        Metrics: {
            /** Against Spread Accuracy */
            against_spread_accuracy?: number | null;
            /** Brier Score */
            brier_score: number;
            /** Margin Mae */
            margin_mae: number;
            /** Market Margin Mae */
            market_margin_mae?: number | null;
            /** N Games */
            n_games: number;
            /**
             * N Spread Games
             * @default 0
             */
            n_spread_games: number;
            /** Spread Game Margin Mae */
            spread_game_margin_mae?: number | null;
        };
        /** ModelSummary */
        ModelSummary: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Is Default */
            is_default: boolean;
            metrics: components["schemas"]["Metrics"];
            /** Name */
            name: string;
            /** Run Id */
            run_id: string;
        };
        /**
         * OddsDay
         * @description One league's odds pulls on one day.
         *
         *     `pulls` and `bytes` come from listing alone. `latest_records` is the only
         *     true record count on the dashboard -- odds objects are small and immutable,
         *     so the newest one per league is cheap to open and count (section 12.4).
         */
        OddsDay: {
            /** Bytes */
            bytes: number;
            /**
             * Day
             * Format: date
             */
            day: string;
            /** Latest At */
            latest_at?: string | null;
            /** Latest Records */
            latest_records?: number | null;
            /** League */
            league: string;
            /** Pulls */
            pulls: number;
        };
        /** PredictResponse */
        PredictResponse: {
            /** Away */
            away: string;
            /** Away Rating */
            away_rating: number;
            /** Away Win Prob */
            away_win_prob: number;
            /** Home */
            home: string;
            /** Home Rating */
            home_rating: number;
            /** Home Win Prob */
            home_win_prob: number;
            /** League */
            league: string;
            /** Model */
            model: string;
            /** Neutral */
            neutral: boolean;
            /** Predicted Spread */
            predicted_spread: number | null;
            /** Run Id */
            run_id: string;
        };
        /** RatingsResponse */
        RatingsResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** League */
            league: string;
            metrics: components["schemas"]["Metrics"];
            /** Model */
            model: string;
            /** Ratings */
            ratings: components["schemas"]["TeamRow"][];
            /** Run Id */
            run_id: string;
            trained_through: components["schemas"]["TrainedThrough"];
        };
        /**
         * SeasonObject
         * @description A season artifact: how big, how fresh, and how many games are in it.
         *
         *     The counts are only on the `.pkl` games artifact -- the possessions and
         *     box-score CSVs beside it are rows, not games, and get `None` rather than a
         *     number that would read as one.
         *
         *     `games` is everything in the file, including games that haven't been played
         *     yet: a season file carries the whole schedule. `games_today` and
         *     `games_in_window` count only *completed* games, because the question they
         *     answer is "did last night's results land", and a fixture list can answer
         *     that yes while the scrape brought back nothing (section 12.4).
         */
        SeasonObject: {
            /** Artifact */
            artifact: string;
            /** Bytes */
            bytes: number;
            /** Games */
            games?: number | null;
            /** Games In Window */
            games_in_window?: number | null;
            /** Games Today */
            games_today?: number | null;
            /** Key */
            key: string;
            /**
             * Last Modified
             * Format: date-time
             */
            last_modified: string;
            /** League */
            league: string;
            /** Year */
            year: number;
        };
        /** TeamRow */
        TeamRow: {
            /** Losses */
            losses: number;
            /** Rank */
            rank: number;
            /** Rating */
            rating: number;
            /** Rd */
            rd: number | null;
            /** Team */
            team: string;
            /** Wins */
            wins: number;
        };
        /**
         * TrainedThrough
         * @description Watermark for the incremental refresh job.
         *
         *     `processed_game_ids` is a set of ids rather than a timestamp because games
         *     get re-fetched and scores corrected; ids are what make the refresh
         *     idempotent. Current season only -- it's a resume marker, not an audit log.
         */
        TrainedThrough: {
            /** Last Game Date */
            last_game_date?: string | null;
            /** Processed Game Ids */
            processed_game_ids?: string[];
            /** Season Year */
            season_year: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** VolumeResponse */
        VolumeResponse: {
            /** Odds */
            odds: components["schemas"]["OddsDay"][];
            /** Seasons */
            seasons: components["schemas"]["SeasonObject"][];
            /**
             * Since
             * Format: date-time
             */
            since: string;
            /** Window Days */
            window_days: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_jobs_api_jobs_get: {
        parameters: {
            query?: {
                /** @description Days of history. Capped at 7 because AWS Batch keeps completed job records for about a week. */
                days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_volume_api_jobs_volume_get: {
        parameters: {
            query?: {
                /** @description Days of history. Capped at 7 because AWS Batch keeps completed job records for about a week. */
                days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VolumeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_leagues_api_leagues_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeagueSummary"][];
                };
            };
        };
    };
    get_ratings_api_leagues__league__ratings_get: {
        parameters: {
            query?: {
                /** @description Defaults to the league's lowest-Brier model. */
                model?: string | null;
            };
            header?: never;
            path: {
                league: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RatingsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    predict_api_predict_get: {
        parameters: {
            query: {
                /** @description e.g. mens */
                league: string;
                /** @description Home team, exactly as the ratings name it. */
                home: string;
                /** @description Away team. */
                away: string;
                /** @description Turns off home advantage. */
                neutral?: boolean;
                /** @description Defaults to the league's lowest-Brier model. */
                model?: string | null;
                /** @description What-if override for the model's home advantage. */
                home_advantage?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PredictResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
